name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Maven tests
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          # Poprawna nazwa parametru wskazującego na wyniki Allure
          allure_results: target/allure-results # <--- ZMIANA
          
          # Ta opcja mówi, gdzie umieścić wygenerowany raport HTML (możemy ją zostawić)
          allure_report: allure-report
          
          # Ta opcja wskaże gałąź do publikacji raportu na GitHub Pages
          gh_pages: gh-pages